[project]
name = "fundrive-baidu"
version = "0.1.2"
description = "fundrive"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
